services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  database:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
